###########################################################################
##### archived 97.5% by just concatenate MVCNN & GVCNN          ####
###########################################################################

#configure data path
data_type: visual
activate_dataset: modelnet40
data_root: &d_r /home/weiyuxuan/data
cora_ft: !join [*d_r, cora/cora.content]
cora_graph: !join [*d_r, cora/cora.cites]
modelnet40_ft: !join [*d_r, features, ModelNet40_mvcnn_gvcnn.mat]
ntu2012_ft: !join [*d_r, features, NTU2012_mvcnn_gvcnn.mat]


#Hypergraph
K_neigs: [1]
m_prob: 1.0
is_probH: False
use_mvcnn_feature_for_structure: True
use_gvcnn_feature_for_structure: True
use_mvcnn_feature_for_train: True
use_gvcnn_feature_for_train: True


#Model
model_type: Inductive
model: CentroidEdgeConvNet
k_sample: 0
k_structured: 0
k_nearest: 0
t_top: 0
n_layers: 2
layer_spec: [2048]
has_bias: True


#Result
# configure result path
result_root: &r_r /home/weiyuxuan/result/AttentionEdgeConvHGNN
ckpt_folder: !join [*r_r, ckpt]


#Train
batch_size: 512
max_epoch: 20
lr: 0.001                # 0.0001 for SGD optimizer
milestones: [200]
gamma: 0.1
drop_out: 0.5
print_freq: 1
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7
with_unlabeled_data: False           # activated only when model_type == Inductive
test_time: 1                          # activated only with sampled models