###########################################################################
##### must check the direction of data_root and result_root before run ####
###########################################################################

#configure data path
data_type: citation
activate_dataset: cora
data_root: &d_r /home/weiyuxuan/data
modelnet40_ft: !join [*d_r, features, ModelNet40_mvcnn_gvcnn.mat]
ntu2012_ft: !join [*d_r, features, NTU2012_mvcnn_gvcnn.mat]
citation_root: !join [*d_r, gcn]
standard_split: True


#Hypergraph
K_neigs: [1]
m_prob: 1.0
is_probH: False
use_mvcnn_feature_for_structure: True
use_gvcnn_feature_for_structure: True
add_self_loop: True


#Model
model_type: Transductive
model: TransGCN_v2
k_sample: 128                   # for model with SampledGraphConvolution layer
k_structured: 64                # for model with MixedNearestConvolution
k_nearest: 64                   # for model with MixedNearestConvolution
k_cluster: 64                   # for model with ClusterGraphConvolution layer
clusters: 200                   # for model with ClusterGraphConvolution layer
adjacent_centers: 2             # for model with ClusterGraphConvolution layer
t_top: 8                        # for model with TopTGraphConvolution layer
n_layers: 2
layer_spec: [128]
has_bias: True


#Result
# configure result path
result_root: &r_r /home/weiyuxuan/result/AttentionEdgeConvHGNN
ckpt_folder: !join [*r_r, ckpt]


#Train
batch_size: 1024                # activated only when model_type == Inductive
max_epoch: 25
milestones: [200]
gamma: 0.1
lr: 0.01
drop_out: 0.5
print_freq: 1
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7
with_unlabeled_data: False        # activated only when model_type == Inductive
test_time: 12                     # activated only with sampled models
