###########################################################################
##### must check the direction of data_root and result_root before run ####
###########################################################################

#configure data path
data_type: citation
activate_dataset: citeseer
data_root: &d_r /home/weiyuxuan/data
modelnet40_ft: !join [*d_r, features, ModelNet40_mvcnn_gvcnn.mat]
ntu2012_ft: !join [*d_r, features, NTU2012_mvcnn_gvcnn.mat]
citation_root: !join [*d_r, gcn]
weibo_ft: !join [*d_r, weibo, mImageTextFeaSel.mat]
weibo_sentiment: !join [*d_r, weibo, mWordSentimentCell_2547_49_1553.mat]


#Hypergraph
K_neigs: [1]
m_prob: 1.0
is_probH: False
use_mvcnn_feature_for_structure: True
use_gvcnn_feature_for_structure: True
add_self_loop: True


#Model
model_type: Transductive
model: TransGCN_v2
k_sample: 128                   # activated only with sampled models
k_structured: 8
k_nearest: 8
t_top: 8                        # activated only with TopTGCN and its variance
n_layers: 2
layer_spec: [256]
has_bias: True


#Result
# configure result path
result_root: &r_r /home/weiyuxuan/result/AttentionEdgeConvHGNN
ckpt_folder: !join [*r_r, ckpt]


#Train
batch_size: 1024                # activated only when model_type == Inductive
max_epoch: 20
milestones: [200]
gamma: 0.1
lr: 0.01
drop_out: 0.5
print_freq: 1
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7
with_unlabeled_data: False        # activated only when model_type == Inductive
test_time: 12                     # activated only with sampled models
